apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: enterprise-platform
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres.yaml
  - redis.yaml
  - oracle.yaml
  - auth.yaml
  - product-inventory.yaml
  - order.yaml
  - payment.yaml
  - notification.yaml
  - gateway.yaml
