apiVersion: apps/v1
kind: Deployment
metadata:
  name: enterprise-payment
  namespace: enterprise-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enterprise-payment
  template:
    metadata:
      labels:
        app: enterprise-payment
    spec:
      containers:
        - name: payment
          image: enterprise-payment:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_DATASOURCE_URL
              value: 'jdbc:oracle:thin:@enterprise-oracle:1521/FREEPDB1'
            - name: SPRING_DATASOURCE_USERNAME
              value: 'payment_service'
            - name: SPRING_DATASOURCE_PASSWORD
              value: '852852'
---
apiVersion: v1
kind: Service
metadata:
  name: enterprise-payment
  namespace: enterprise-platform
spec:
  selector:
    app: enterprise-payment
  ports:
    - port: 8084
      targetPort: 8084
